#!/usr/bin/env python3
"""
NYC Taxi AI Agent — FastAPI entrypoint
========================================

Exposes the LangChain SQL agent over HTTP so it can be queried in
natural language and demoed live during the project presentation.

Endpoints:
    GET  /health          -> liveness check
    POST /ask              -> {"question": "..."} -> natural-language answer
    GET  /docs              -> interactive Swagger UI (auto-generated by FastAPI)

Run locally (outside Docker) for quick iteration:
    uvicorn main:app --reload --port 8000
"""

import logging

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from agent import ask_agent, get_agent_executor

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-8s %(message)s")
logger = logging.getLogger("ai_agent.main")

app = FastAPI(
    title="NYC Taxi AI Agent",
    description="Natural-language analytics layer on top of the ClickHouse taxi_trips data.",
    version="1.0.0",
)

# Loosened CORS so the FastAPI /docs page (and any quick frontend) can call this freely in a demo.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class Question(BaseModel):
    question: str


class Answer(BaseModel):
    question: str
    answer: str


@app.on_event("startup")
def _warm_up_agent() -> None:
    """Build the agent executor once at startup instead of per-request."""
    try:
        get_agent_executor()
        logger.info("AI agent initialized and ready.")
    except Exception:
        # Don't crash the whole service if ClickHouse/the LLM isn't reachable yet —
        # log it and let /ask surface a clear error on the next request instead.
        logger.exception("Agent failed to initialize at startup.")


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/ask", response_model=Answer)
def ask(payload: Question):
    if not payload.question or not payload.question.strip():
        raise HTTPException(status_code=400, detail="question must not be empty")

    try:
        answer_text = ask_agent(payload.question)
    except Exception as exc:  # noqa: BLE001 - want a clean 500 with a readable message in the demo
        logger.exception("Agent failed to answer question: %s", payload.question)
        raise HTTPException(status_code=500, detail=f"agent error: {exc}") from exc

    return Answer(question=payload.question, answer=answer_text)
